//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngieFileConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EngieFileConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clipboard_image {
            get {
                object obj = ResourceManager.GetObject("clipboard_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon EngieIcon {
            get {
                object obj = ResourceManager.GetObject("EngieIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Structure and terrain grid definitions
        ///
        ///; The system will read line &quot;0=&quot;, &quot;1=&quot;, &quot;2=&quot; etc, and will see any &apos;x&apos; or &apos;X&apos;
        ///; characters as cells of the foundation.
        ///; Since the read aborts after finding an empty line, empty lines in between
        ///; HAVE to added. I padded everything with other characters to show a rectangular
        ///; shape, which solves that problem.
        ///
        ///; The origin (0,0) point of the grid can be specified with the keys &quot;XShift=&quot;
        ///; and &quot;YShift=&quot;. Basically, this is the amount to subtract from the gi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string grids {
            get {
                return ResourceManager.GetString("grids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IniHandler {
            get {
                object obj = ResourceManager.GetObject("IniHandler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Structures]
        ///0=WEAP
        ///1=GTWR
        ///2=ATWR
        ///3=OBLI
        ///4=HQ
        ///5=GUN
        ///6=FACT
        ///7=PROC
        ///8=SILO
        ///9=HPAD
        ///10=SAM
        ///11=AFLD
        ///12=NUKE
        ///13=NUK2
        ///14=HOSP
        ///15=PYLE
        ///16=ARCO
        ///17=FIX
        ///18=BIO
        ///19=HAND
        ///20=TMPL
        ///21=EYE
        ///22=MISS
        ///23=V01
        ///24=V02
        ///25=V03
        ///26=V04
        ///27=V05
        ///28=V06
        ///29=V07
        ///30=V08
        ///31=V09
        ///32=V10
        ///33=V11
        ///34=V12
        ///35=V13
        ///36=V14
        ///37=V15
        ///38=V16
        ///39=V17
        ///40=V18
        ///41=V19
        ///42=V20
        ///43=V21
        ///44=V22
        ///45=V23
        ///46=V24
        ///47=V25
        ///48=V26
        ///49=V27
        ///50=V28
        ///51=V29
        ///52=V30
        ///53=V31
        ///54=V32
        ///55=V33
        ///56=V34
        ///57=V35
        ///58=V36
        ///59=V37
        ///60=SBAG
        ///61= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string structs {
            get {
                return ResourceManager.GetString("structs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Terrain]
        ///0=T01
        ///1=T02
        ///2=T03
        ///3=T04
        ///4=T05
        ///5=T06
        ///6=T07
        ///7=T08
        ///8=T09
        ///9=T10
        ///10=T11
        ///11=T12
        ///12=T13
        ///13=T14
        ///14=T15
        ///15=T16
        ///16=T17
        ///17=T18
        ///18=SPLIT2
        ///19=SPLIT3
        ///20=TC01
        ///21=TC02
        ///22=TC03
        ///23=TC04
        ///24=TC05
        ///25=ROCK1
        ///26=ROCK2
        ///27=ROCK3
        ///28=ROCK4
        ///29=ROCK5
        ///30=ROCK6
        ///31=ROCK7
        ///
        ///[T01]
        ///OverlapList=T01Overlap
        ///OccupyList=T01Occupy
        ///Unknown3=1
        ///HitPoints=600
        ///NameID=38
        ///Invulnerable=No
        ///Unknown7=1
        ///Unknown8=0
        ///Unknown9=0
        ///Unknown10=0
        ///Unknown11=1
        ///Unknown12=0
        ///Unknown13=1
        ///Options=28639349
        ///Theaters=Tempe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string terrain {
            get {
                return ResourceManager.GetString("terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] th_desert {
            get {
                object obj = ResourceManager.GetObject("th_desert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] th_temperate {
            get {
                object obj = ResourceManager.GetObject("th_temperate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TileSets]
        ///0=CLEAR1
        ///1=W1
        ///2=W2
        ///3=SH1
        ///4=SH2
        ///5=SH3
        ///6=SH4
        ///7=SH5
        ///8=SH11
        ///9=SH12
        ///10=SH13
        ///11=SH14
        ///12=SH15
        ///13=S01
        ///14=S02
        ///15=S03
        ///16=S04
        ///17=S05
        ///18=S06
        ///19=S07
        ///20=S08
        ///21=S09
        ///22=S10
        ///23=S11
        ///24=S12
        ///25=S13
        ///26=S14
        ///27=S15
        ///28=S16
        ///29=S17
        ///30=S18
        ///31=S19
        ///32=S20
        ///33=S21
        ///34=S22
        ///35=S23
        ///36=S24
        ///37=S25
        ///38=S26
        ///39=S27
        ///40=S28
        ///41=S29
        ///42=S30
        ///43=S31
        ///44=S32
        ///45=S33
        ///46=S34
        ///47=S35
        ///48=S36
        ///49=S37
        ///50=S38
        ///51=SH32
        ///52=SH33
        ///53=SH20
        ///54=SH21
        ///55=SH22
        ///56=SH23
        ///57=BR1
        ///58=BR2
        ///59=BR3
        ///60=BR4
        ///61=BR5
        ///62 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tilesets {
            get {
                return ResourceManager.GetString("tilesets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TileSets]
        ///0=CLEAR1
        ///1=W1
        ///2=W2
        ///3=SH1
        ///4=SH2
        ///5=SH3
        ///6=SH4
        ///7=SH5
        ///8=SH11
        ///9=SH12
        ///10=SH13
        ///11=SH14
        ///12=SH15
        ///13=S01
        ///14=S02
        ///15=S03
        ///16=S04
        ///17=S05
        ///18=S06
        ///19=S07
        ///20=S08
        ///21=S09
        ///22=S10
        ///23=S11
        ///24=S12
        ///25=S13
        ///26=S14
        ///27=S15
        ///28=S16
        ///29=S17
        ///30=S18
        ///31=S19
        ///32=S20
        ///33=S21
        ///34=S22
        ///35=S23
        ///36=S24
        ///37=S25
        ///38=S26
        ///39=S27
        ///40=S28
        ///41=S29
        ///42=S30
        ///43=S31
        ///44=S32
        ///45=S33
        ///46=S34
        ///47=S35
        ///48=S36
        ///49=S37
        ///50=S38
        ///51=SH32
        ///52=SH33
        ///53=SH20
        ///54=SH21
        ///55=SH22
        ///56=SH23
        ///57=BR1
        ///58=BR2
        ///59=BR3
        ///60=BR4
        ///61=BR5
        ///62 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tilesets2 {
            get {
                return ResourceManager.GetString("tilesets2", resourceCulture);
            }
        }
    }
}
