//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngieFileConverter.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EngieFileConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clipboard_image {
            get {
                object obj = ResourceManager.GetObject("clipboard_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon EngieIcon {
            get {
                object obj = ResourceManager.GetObject("EngieIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IniHandler {
            get {
                object obj = ResourceManager.GetObject("IniHandler", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_WindowsAPICodePack {
            get {
                object obj = ResourceManager.GetObject("Microsoft_WindowsAPICodePack", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_WindowsAPICodePack_Shell {
            get {
                object obj = ResourceManager.GetObject("Microsoft_WindowsAPICodePack_Shell", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] th_desert {
            get {
                object obj = ResourceManager.GetObject("th_desert", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] th_temperate {
            get {
                object obj = ResourceManager.GetObject("th_temperate", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [TileSets]
        ///0=CLEAR1
        ///1=W1
        ///2=W2
        ///3=SH1
        ///4=SH2
        ///5=SH3
        ///6=SH4
        ///7=SH5
        ///8=SH11
        ///9=SH12
        ///10=SH13
        ///11=SH14
        ///12=SH15
        ///13=S01
        ///14=S02
        ///15=S03
        ///16=S04
        ///17=S05
        ///18=S06
        ///19=S07
        ///20=S08
        ///21=S09
        ///22=S10
        ///23=S11
        ///24=S12
        ///25=S13
        ///26=S14
        ///27=S15
        ///28=S16
        ///29=S17
        ///30=S18
        ///31=S19
        ///32=S20
        ///33=S21
        ///34=S22
        ///35=S23
        ///36=S24
        ///37=S25
        ///38=S26
        ///39=S27
        ///40=S28
        ///41=S29
        ///42=S30
        ///43=S31
        ///44=S32
        ///45=S33
        ///46=S34
        ///47=S35
        ///48=S36
        ///49=S37
        ///50=S38
        ///51=SH32
        ///52=SH33
        ///53=SH20
        ///54=SH21
        ///55=SH22
        ///56=SH23
        ///57=BR1
        ///58=BR2
        ///59=BR3
        ///60=BR4
        ///61=BR5
        ///62 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tilesets {
            get {
                return ResourceManager.GetString("tilesets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [TileSets]
        ///0=CLEAR1
        ///1=W1
        ///2=W2
        ///3=SH1
        ///4=SH2
        ///5=SH3
        ///6=SH4
        ///7=SH5
        ///8=SH11
        ///9=SH12
        ///10=SH13
        ///11=SH14
        ///12=SH15
        ///13=S01
        ///14=S02
        ///15=S03
        ///16=S04
        ///17=S05
        ///18=S06
        ///19=S07
        ///20=S08
        ///21=S09
        ///22=S10
        ///23=S11
        ///24=S12
        ///25=S13
        ///26=S14
        ///27=S15
        ///28=S16
        ///29=S17
        ///30=S18
        ///31=S19
        ///32=S20
        ///33=S21
        ///34=S22
        ///35=S23
        ///36=S24
        ///37=S25
        ///38=S26
        ///39=S27
        ///40=S28
        ///41=S29
        ///42=S30
        ///43=S31
        ///44=S32
        ///45=S33
        ///46=S34
        ///47=S35
        ///48=S36
        ///49=S37
        ///50=S38
        ///51=SH32
        ///52=SH33
        ///53=SH20
        ///54=SH21
        ///55=SH22
        ///56=SH23
        ///57=BR1
        ///58=BR2
        ///59=BR3
        ///60=BR4
        ///61=BR5
        ///62 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tilesets2 {
            get {
                return ResourceManager.GetString("tilesets2", resourceCulture);
            }
        }
    }
}
